### ISSUE TITLE
Coloring suggestions

### ISSUE THREAD

**Issue by autumncpp** [ValentinTT/ida-debugger#1]
Hi there, awesome work you've done so far! I took a look at this theme earlier today and had a few suggestions regarding the color scheme. I'm planning to mess around with the theme when I have some free time, so I could probably turn this into a pull request in the future. I will also be embedding comparisons alongside IDA's default dark theme for reference.

### Pseudocode
* Casting is dark-gray, this makes it hard to read. I think a brighter color would be much more appropriate.
![](https://i.invalid.gg/ida64_8WsyVuOCPp.png)
vs
![](https://i.invalid.gg/ida64_R3hEZBAt0m.png)
* (non-imported) Function calls, variable references, parameter references, .data & .rdata variable references, and comments are all peach. This makes differentiation at a glance very hard to do.
![](https://i.invalid.gg/ida64_N2hpwYph1k.png)
vs
![](https://i.invalid.gg/ida64_mwPzcalfiT.png)
* Function definition and some variable definitions are gray, making it hard to read. These would be better as a brighter color.
![](https://i.invalid.gg/ida64_noqu9VHFe9.png)
vs
![](https://i.invalid.gg/ida64_fV3GZfmdP5.png)

### Main View
* Soo much peach
![](https://i.invalid.gg/ida64_4bRhPneBM0.png)
vs
![](https://i.invalid.gg/ida64_2SkZNcCbOn.png)
* Some variable names within .data are peach, some are red. These should be the same color.
![](https://i.invalid.gg/ida64_KT9zwdM9Gl.png)
vs
![](https://i.invalid.gg/ida64_Mdl8Q5tHTM.png)
* Personally, I think most line prefixes should have more muted colors. Excluding the following segments: imports, library functions, lumina, single line instructions, and unexplored bytes. Some of the color choices in my opinion are a bit odd, such as unexplored bytes being red, which catches my attention for really no reason.
![](https://i.invalid.gg/ida64_IFfXypx6M4.png)
vs
![](https://i.invalid.gg/ida64_Svyv1QwSmf.png)

### Hex-View
* Maybe these two colors should be flipped? (bytes and address)
![](https://i.invalid.gg/ida64_3IYew0AUTp.png)
vs
![](https://i.invalid.gg/ida64_diBVN56NCM.png)

Just my 2 cents, hopefully I don't sound entirely crazy! I'll look into making some style changes that follows to catppuccin theme that fixes some of these issues and if you'd like, I could put them in a pull request.

Good work!

**Comment by sgoudham** [comment]
Hiya 👋, just also putting in my 2 cents if that's alright. 

We do have [code editor style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#code-editors) that we recently defined to try and help make the syntax highlighting  (functions, comments, etc) more consistent across our ports. Obviously, the terms won't directly match here but I think it would be useful to try and follow it!

**Comment by ValentinTT** [comment]
Thanks 🙏🙏 for the pr @autumncpp !! I'm closing this issue now
